thirvusoft/paver_sgp

ganapathy_pavers/custom/js/item.js, ganapathy_pavers/custom/js/sales_order.js, ganapathy_pavers/custom/py/item.py, ganapathy_pavers/custom/py/item_group.py, ganapathy_pavers/custom/py/sales_invoice.py, ganapathy_pavers/custom/py/sales_order.py, ganapathy_pavers/ganapathy_pavers/doctype/compound_wall/compound_wall.json, ganapathy_pavers/ganapathy_pavers/doctype/item_detail_compound_wall/item_detail_compound_wall.json, ganapathy_pavers/hooks.py
=> Compout wal fllow Development

ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.js, ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.json, ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.py
=> TS Customer Ledger Summary

ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.py
=> Delivery Amount

ganapathy_pavers/custom/js/employee_atten_tool.js, ganapathy_pavers/ganapathy_pavers/report/ts_customer_ledger_summary/ts_customer_ledger_summary.py, ganapathy_pavers/hooks.py
=> Opening bls

ganapathy_pavers/custom/py/purchase_order.py, ganapathy_pavers/hooks.py, ganapathy_pavers/utils/py/purchase_order.py
- Notification will be sent if Purchase order Required by date is equal to today date and the required % == 0
- Screenshot:
=> Notifications for Purchase order

ganapathy_pavers/custom/py/vehicle_log.py, ganapathy_pavers/ganapathy_pavers/doctype/service_item/service_item.js, ganapathy_pavers/ganapathy_pavers/doctype/service_item/service_item.json, ganapathy_pavers/ganapathy_pavers/doctype/service_item/service_item.py, ganapathy_pavers/ganapathy_pavers/doctype/service_item/test_service_item.py, ganapathy_pavers/ganapathy_pavers/doctype/vehicle_log_service/vehicle_log_service.json, ganapathy_pavers/ganapathy_pavers/doctype/vehicle_log_service/vehicle_log_service.py, ganapathy_pavers/utils/py/maintenance_details.py, ganapathy_pavers/utils/py/vehicle_log.py
1. In Vehicle, inside the child table, the "Service item" has been changed to Link field. 
2. In Vehicle Log the existing Service table has been hidden and a new child table "Vehicle Log Service" has been created.
3. Code changes to prevent errors from the changes done in (2.).
4. Doctype called Service Item has been created.
5. Remove some unnecessary code from maintenance details.
6. Screenshots:
Vehicle Log
Vehicle:
Service Item:
=> Vehicle & Vehicle Log Fixes

ganapathy_pavers/custom/py/vehicle_log.py
A small code change to fix 'Kilometers after last service' not updating
=> Fixed 'Kilometers after last service' not updating

ganapathy_pavers/custom/js/sales_order.js, ganapathy_pavers/custom/py/sales_order.py
Compound wall calculation depends on sales uom
ba
=> Compound Wall Calculation

ganapathy_pavers/ganapathy_pavers/doctype/employee_advance_details/employee_advance_details.json, ganapathy_pavers/ganapathy_pavers/doctype/employee_advance_tool/employee_advance_tool.js, ganapathy_pavers/ganapathy_pavers/doctype/employee_advance_tool/employee_advance_tool.py, ganapathy_pavers/ganapathy_pavers/doctype/employee_bonus_details/employee_bonus_details.json, ganapathy_pavers/ganapathy_pavers/doctype/employee_bonus_tool/employee_bonus_tool.py
=> order the employee name as ascending

ganapathy_pavers/ganapathy_pavers/doctype/employee_advance_tool/employee_advance_tool.py
bug fixed in advance employee tool
=> bug fixed in advance tool

ganapathy_pavers/custom/py/purchase_order.py
Purchase order notification subject changed to "Goods for this PO('Purchase Order no') has not been received"
=> Subject changed in Purchase Order notification

ganapathy_pavers/custom/js/delivery_note.js
=> create a button in delivery note

ganapathy_pavers/custom/py/employee_atten_tool.py, ganapathy_pavers/custom/py/ts_employee_atten_tool.js, ganapathy_pavers/ganapathy_pavers/custom/employee_checkin.json, ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.json
=> Employee checkout update

ganapathy_pavers/custom/py/sales_order.py, ganapathy_pavers/hooks.py
sales order type fixes, while choosing the type, in item table they only choose that type. If they do not choose the correct it shows the error.
=> sales order type fixes

ganapathy_pavers/utils/py/item.py
Hide brand if Item group is "Compound Wall"
=> Minor Fix in Item table

ganapathy_pavers/custom/py/sales_order.py, ganapathy_pavers/custom/py/site_work.py, ganapathy_pavers/ganapathy_pavers/doctype/compound_wall/compound_wall.json, ganapathy_pavers/ganapathy_pavers/doctype/pavers/pavers.json, ganapathy_pavers/ganapathy_pavers/doctype/raw_materials/raw_materials.json
Site Work Calculation Fixes based on Stock Qty and UOM Conversion
=> Site Work Calculation Fixes

ganapathy_pavers/custom/py/site_work.py
=> Print statements removed

ganapathy_pavers/ganapathy_pavers/print_format/quotation/quotation.json
quotation print format alignment
change
=> Quotation print format

ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.py
Chores:bug fix
Added jobworker advance in total field
=> Chores:bug fix

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py
=> fix:updated Naming Series

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py
=> fix:validation

ganapathy_pavers/custom/py/employee_atten_tool.py, ganapathy_pavers/custom/py/ts_employee_atten_tool.js, ganapathy_pavers/ganapathy_pavers/doctype/ts_employee_attendance_tool/ts_employee_attendance_tool.json
=> CHECKIN Alert

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py, ganapathy_pavers/ganapathy_pavers/doctype/raw_material_consumption/raw_material_consumption.json, ganapathy_pavers/ganapathy_pavers/doctype/usb_setting/usb_setting.js, ganapathy_pavers/ganapathy_pavers/doctype/usb_setting/usb_setting.json
=> fix changes in manufacture

ganapathy_pavers/custom/py/employee_atten_tool.py, ganapathy_pavers/hooks.py
=> attendance cancel

ganapathy_pavers/custom/py/payment_entry.py, ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/ts_customer_receivable_summary.js, ganapathy_pavers/ganapathy_pavers/report/ts_customer_receivable_summary/ts_customer_receivable_summary.py
=> site work filter in customer ledger summary

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing_list.js
=> item calculation

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py, ganapathy_pavers/ganapathy_pavers/doctype/usb_setting/usb_setting.json
=> item add in table

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py
=> added field

ganapathy_pavers/backup/report_view.js, ganapathy_pavers/custom/py/reportview.py
=>  Total Row for Report Builder

ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.js, ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.json, ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.py
=> site work wise delivery report

ganapathy_pavers/custom/py/employee_atten_tool.py, ganapathy_pavers/custom/py/ts_employee_atten_tool.js
Just Apply Filters For Active Employees
=> inactive_employees_filter

ganapathy_pavers/custom/js/employee.js, ganapathy_pavers/ganapathy_pavers/doctype/contractor_commission_rate/contractor_commission_rate.js, ganapathy_pavers/ganapathy_pavers/doctype/contractor_commission_rate/contractor_commission_rate.json, ganapathy_pavers/ganapathy_pavers/doctype/contractor_commission_rate/contractor_commission_rate.py, ganapathy_pavers/ganapathy_pavers/doctype/contractor_commission_rate/test_contractor_commission_rate.py, ganapathy_pavers/hooks.py, ganapathy_pavers/utils/py/salary_slip.py
Contractor Welfare and Labour Worker  designation salary slip modification
=> salary_slip_contractor_welfare

ganapathy_pavers/custom/js/delivery_note.js, ganapathy_pavers/custom/js/sales_invoice.js
Qty round off for square foot conversion in delivery note
=> Manufacturing

ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.py
Bug Fix: Group By filter not added
=> Fixes in Report

ganapathy_pavers/hooks.py, ganapathy_pavers/patches.txt, ganapathy_pavers/patches/quotation_options, ganapathy_pavers/utils/py/quotation.py
Order Type options have been changed to
- Compound Walls
- Pavers
and added patches and hooks for it.
=> Quotation fixes

ganapathy_pavers/hooks.py, ganapathy_pavers/utils/py/payment_entry.py
field customization payment entry
=> field customization payment entry

ganapathy_pavers/ganapathy_pavers/doctype/shot_blast_costing/shot_blast_costing.js, ganapathy_pavers/ganapathy_pavers/doctype/shot_blast_costing/shot_blast_costing.py
=> filter and uom conversion

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/report/daily_working_area_wise_worked_hrs/daily_working_area_wise_worked_hrs.json
=> Daily Working Area Wise Worked Hrs

ganapathy_pavers/custom/py/stock_entry.py, ganapathy_pavers/ganapathy_pavers/doctype/cw_manufacturing/cw_manufacturing.py, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.py, ganapathy_pavers/hooks.py, ganapathy_pavers/utils/py/stock_entry.py
Material Manufacturing and cw manufacturing doctype stock entry creation basic rate fetching error fixes
=> stock entry fixes

ganapathy_pavers/ganapathy_pavers/workspace/hr_cycle/hr_cycle.json
=> Report added HR Cycle

ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/site_work_completion___report.py
Export  to Excel issue fix in site work completion report
=> export issue fix

ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/site_work_completion___report.js, ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/site_work_completion___report.json, ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/site_work_completion___report.py
Report Group by: Site work and Job Worker
=> Site Work Completion Report customization

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json, ganapathy_pavers/ganapathy_pavers/doctype/shot_blast_costing/shot_blast_costing.js, ganapathy_pavers/ganapathy_pavers/doctype/shot_blast_costing/shot_blast_costing.py, ganapathy_pavers/ganapathy_pavers/doctype/shot_blast_items/shot_blast_items.json, ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/site_work_completion___report.py
Shot Blasting Qty Will fetch only available qty
=> Shot Blasting Qty Customization

ganapathy_pavers/__init__.py, ganapathy_pavers/ganapathy_pavers/report/monthly_compound_wall_production_report/monthly_compound_wall_production_report.js, ganapathy_pavers/ganapathy_pavers/report/monthly_compound_wall_production_report/monthly_compound_wall_production_report.json, ganapathy_pavers/ganapathy_pavers/report/monthly_compound_wall_production_report/monthly_compound_wall_production_report.py
Monthly compound wall production Report
=> Monthly compound wall production Report

ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.js, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.json, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.py
Item Wise Monthly Paver Production Report
=> monthly_paver_production_report

ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.js, ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.json, ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.py, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.js, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.json, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.py
Daily Paver Production Register
=> Daily paver production

ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.js, ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.json, ganapathy_pavers/ganapathy_pavers/report/daily_paver_production_register/daily_paver_production_register.py, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.js, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.json, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.py, ganapathy_pavers/ganapathy_pavers/report/monthly_paver_production_report/monthly_paver_production_report.js, ganapathy_pavers/ganapathy_pavers/report/monthly_paver_production_report/monthly_paver_production_report.json, ganapathy_pavers/ganapathy_pavers/report/monthly_paver_production_report/monthly_paver_production_report.py
Monthly Paver Production Register
=> Monthly paver production register

ganapathy_pavers/ganapathy_pavers/report/daily_lego_post_production/daily_lego_post_production.js, ganapathy_pavers/ganapathy_pavers/report/daily_lego_post_production/daily_lego_post_production.json, ganapathy_pavers/ganapathy_pavers/report/daily_lego_post_production/daily_lego_post_production.py
=> lego production-daily

ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_cw_production_report/itemwise_monthly_cw_production_report.py, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_lego_block_production_report/itemwise_monthly_lego_block_production_report.py, ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_paver_production_report/itemwise_monthly_paver_production_report.py
=> add no of days in itemwise monthly reports

ganapathy_pavers/ganapathy_pavers/doctype/cw_manufacturing/cw_manufacturing.py
group by item and sum of their produced qty,damged qty,ts production qty
=> group by item and sum of their produced qty,damged qty,ts production qty

ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.js, ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.py
salary balance fetch from last salary slip or inside employee salary balance
=> Jw salarybalance

ganapathy_pavers/custom/py/batch_qty.py
batch qty fetching and updated in bin actual qty
=> Batch qty fix

ganapathy_pavers/custom/js/journal_entry.js, ganapathy_pavers/ganapathy_pavers/doctype/expense_accounts/expense_accounts.py
=> monthly cost fixes

ganapathy_pavers/custom/js/journal_entry.js, ganapathy_pavers/custom/py/vehicle_overwrite.py, ganapathy_pavers/hooks.py
in vehicle log based on select purpose (fuel,service) did not change the odometer value in vehicle last odometer value
=> Vehicle log changes

ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.html, ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.py
job worker report prinformat customization
=> job worker report prinformat customization

ganapathy_pavers/ganapathy_pavers/doctype/expense_account_common_groups/expense_account_common_groups.json, ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.html, ganapathy_pavers/ganapathy_pavers/report/job_worker___report/job_worker___report.py
=> Edit dcotype

ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/running_order_report/running_order_report.js, ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/running_order_report/running_order_report.json, ganapathy_pavers/ganapathy_pavers/report/site_work_completion___report/running_order_report/running_order_report.py
=> Running Order Report

ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.js, ganapathy_pavers/ganapathy_pavers/doctype/material_manufacturing/material_manufacturing.json
=> change function to button

ganapathy_pavers/custom/py/employee_checkin.py, ganapathy_pavers/hooks.py
create attendance based on one checkin
=> create attendance based on one checkin

ganapathy_pavers/__init__.py, ganapathy_pavers/utils/py/salary_slip.py
init file changing for salary structure formula
=> init file changes

ganapathy_pavers/ganapathy_pavers/report/monthly_inward_transport_report/monthly_inward_transport_report.py, ganapathy_pavers/ganapathy_pavers/report/monthly_transport_report/monthly_transport_report.py, ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.js, ganapathy_pavers/ganapathy_pavers/report/site_work_wise_delivery_report/site_work_wise_delivery_report.py
new fields - No of days, No of trips, mileage, pending due, Insurance end,
Tyre cost calculation change
For inward report - profit field - (landed cost voucher amount - expense amount)
=> Monthly transport report

ganapathy_pavers/custom/py/lead.py, ganapathy_pavers/custom/py/site_work.py, ganapathy_pavers/ganapathy_pavers/report/delivery_report/delivery_report.py, ganapathy_pavers/hooks.py
override the set status function in validate
=> override the set status function in validate

ganapathy_pavers/ganapathy_pavers/report/delivery_report/delivery_report.js, ganapathy_pavers/ganapathy_pavers/report/delivery_report/delivery_report.py, ganapathy_pavers/hooks.py
change dont show status in delivery note
=> change dont show status in delivery note

ganapathy_pavers/backup/report/customer_ledger_summary/customer_ledger_summary.html, ganapathy_pavers/backup/report/customer_ledger_summary/customer_ledger_summary.js, ganapathy_pavers/backup/report/customer_ledger_summary/customer_ledger_summary.py
customer ledger summary report
=> customer ledger summary report

ganapathy_pavers/backup/report/general_ledger/general_ledegr.js, ganapathy_pavers/backup/report/general_ledger/general_ledger.py
=> Credit note gl
